# Use the PHP 7.3 runtime by replacing "php72" below with "php73"
runtime: php73

entrypoint: serve loginpage.php

handlers:
- url: /*
  static_dir: .
- url: /styles/*
  static_dir: styles
- url: /img/*
  static_dir: img