runtime: php73

# handlers:
# - url: /
#   script: src/loginpage.php
# - url: /loginpage\.php
#   script: src/loginpage.php
# - url: /homepage\.php
#   script: src/homepage.php
# - url: /accountpage\.php
#   script: src/accountpage.php
# - url: /allgames\.php
#   script: src/allgames.php
# - url: /newgame\.php
#   script: src/newgame.php

handlers:
- url: /styles/*
  static_dir: src/styles
- url: /img/*
  static_dir: src/img
- url: /.*
  script: auto

env_variables:
  CLOUDSQL_USER: root
  CLOUDSQL_DB: jeopardydb
  CLOUDSQL_PASSWORD: admin
  CLOUDSQL_CONN_NAME: cs3250-jeopardy:us-east4:jeopardydb
  GOOGLE_CLOUD_PROJECT: cs3250-jeopardy
