# Use the PHP 7.3 runtime by replacing "php72" below with "php73"
runtime: php55

entrypoint: serve src/loginpage.php

#- url: /
#  static_dir: src

handlers:
- url: /login
  script: src/loginpage.php
- url: /home
  script: src/homepage.php
- url: /(.+\.php)$
  script: auto
- url: /styles/*
  static_dir: src/styles
- url: /img/*
  static_dir: src/img