# Use the PHP 5.5 runtime so the routing is easier
runtime: php55

handlers:
- url: /
  script: src/loginpage.php
- url: /login
  script: src/loginpage.php
- url: /home
  script: src/homepage.php
- url: /styles/*
  static_dir: src/styles
- url: /img/*
  static_dir: src/img