# Use the PHP 7.3 runtime by replacing "php72" below with "php73"
runtime: php73

entrypoint: serve src/loginpage.php

handlers:
- url: /
  static_dir: src
- url: /styles/*
  static_dir: src/styles
- url: /img/*
  static_dir: src/img